apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    kubernetes.io/description: Anyscale NodePool for GPU workloads
  name: anyscale-gpu
spec:
  disruption:
    budgets:
    - nodes: 30%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: "1000"
    memory: 4000Gi
  weight: 100
  template:
    metadata:
      labels:
        karpenter.sh/capacity-type: on-demand
        anyscale.com/gpu-enabled: "true"
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.azure.com
        kind: AKSNodeClass
        name: anyscale-nodeclass
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.azure.com/sku-gpu-name
        operator: Exists
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
      - key: node.anyscale.com/capacity-type
        value: ON_DEMAND
        effect: NoSchedule
      - key: node.anyscale.com/accelerator-type
        value: GPU
        effect: NoSchedule
      - key: nvidia.com/gpu
        effect: NoSchedule
