apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-plugin-hook-injector
spec:
  template:
    spec:
      priorityClassName: system-node-critical
      initContainers:
        - name: install-hook-script
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              cp /scripts/demo-hook.sh /host/usr/local/sbin/demo-hook.sh
              chmod +x /host/usr/local/sbin/demo-hook.sh
              cp /hooks/* /host/usr/share/containers/oci/hooks.d/
          volumeMounts:
            - name: demo-hook-script
              mountPath: /scripts
              readOnly: true
            - name: host-sbin
              mountPath: /host/usr/local/sbin
            - name: hook-injector-hooks
              mountPath: /hooks
              readOnly: true
            - name: usr-share-hooks-d
              mountPath: /host/usr/share/containers/oci/hooks.d
      containers:
        - name: plugin
          image: plugin
          args:
            - "-idx"
            - "10"
          resources:
            requests:
              cpu: "2m"
              memory: "5Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: nri-socket
              mountPath: /var/run/nri/nri.sock
            - name: etc-hooks-d
              mountPath: /etc/containers/oci/hooks.d
              readOnly: true
            - name: usr-share-hooks-d
              mountPath: /usr/share/containers/oci/hooks.d
              readOnly: true
            - name: libexec-hooks-d
              mountPath: /usr/libexec/oci/hooks.d
              readOnly: true
      volumes:
        - name: nri-socket
          hostPath:
            path: /var/run/nri/nri.sock
            type: Socket
        - name: etc-hooks-d
          hostPath:
            path: /etc/containers/oci/hooks.d
            type: DirectoryOrCreate
        - name: usr-share-hooks-d
          hostPath:
            path: /usr/share/containers/oci/hooks.d
            type: DirectoryOrCreate
        - name: libexec-hooks-d
          hostPath:
            path: /usr/libexec/oci/hooks.d
            type: DirectoryOrCreate
        - name: demo-hook-script
          configMap:
            name: demo-hook-script
            defaultMode: 0755
        - name: hook-injector-hooks
          configMap:
            name: hook-injector-hooks
        - name: host-sbin
          hostPath:
            path: /usr/local/sbin
            type: DirectoryOrCreate
